services:
  postgres:
    container_name: postgres
    image: postgres:bullseye
    env_file: "./.env"
    environment:
      PGDATA: /var/lib/postgresql/t3_data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - t3_data:/var/lib/postgresql/t3_data/pgdata
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    restart: unless-stopped
    tty: true
    stdin_open: true

  backend:
    build: .
    env_file: "./.env"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  t3_data:

